name: prob_ar_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  freezed_annotation: 2.0.3
  google_fonts: 2.3.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  flutter_svg: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: 0.17.0
  pull_to_refresh: ^2.0.0
  
dev_dependencies: 
  build_runner: ^2.1.11
  lint: ^1.8.2
  json_serializable: ^6.2.0
  hive_generator: ^1.1.3
  retrofit_generator: ^4.0.1
  freezed: ^2.0.3+1
  flutter_launcher_icons: ^0.9.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

